/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

import java.util.ArrayList;

import javax.swing.DefaultListModel;

/**
 *
 * @author Ryanp
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jb_atualizar = new javax.swing.JButton();
        jb_voltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_contatos = new javax.swing.JList<>();
        jl_usuario = new javax.swing.JLabel();
        jb_conversa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_atualizar.setContentAreaFilled(false);
        jb_atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 43, 150, 50));

        jb_voltar.setContentAreaFilled(false);
        jb_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 120, 40));

        jl_contatos.setBackground(new java.awt.Color(46, 115, 155));
        jScrollPane2.setViewportView(jl_contatos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 490, 450));
        getContentPane().add(jl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 36, 310, 60));

        jb_conversa.setBackground(new java.awt.Color(46, 100, 155));
        getContentPane().add(jb_conversa, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 583, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/TelaHome.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 560, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jb_voltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.setVisible(false);
        
        LoginView login = new LoginView();
        login.setVisible(true);
    }              
    
    
    public void atualizarContatos(ArrayList<String> meuNome) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for(String nome : meuNome) {
            model.addElement(nome);
        }
        jl_contatos.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_atualizar;
    private javax.swing.JButton jb_conversa;
    private javax.swing.JButton jb_voltar;
    private javax.swing.JList<String> jl_contatos;
    private javax.swing.JLabel jl_usuario;
    // End of variables declaration                   
}
